sudo: required

os:
  - linux

services:
  - docker

before_install: 
  - docker build -t geo-jupyter .

script:
  - docker images | grep "geo-jupyter"
  - docker run -it --rm geo-jupyter R --version
  - docker run -it --rm geo-jupyter jupyter --version
  - docker run -d -p 8888:8888 --name geo-jupyter geo-jupyter
  - sleep 3 && docker ps | grep geo-jupyter

after_script:
  - docker stop geo-jupyter
  - docker rm $(docker ps -aq)
  - docker rmi geo-jupyter
